name: habit_tracker
description: Minimalist Web-First Habit Tracker in Material 3
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2

flutter:
  uses-material-design: true
